# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-caffeinated:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      
      - run:
          name: Build Caffeinated
          command: cd caffeinated && bash build.sh

      # Produce the Windows Artifact
      - run:
          name: ZIP the Windows (AMD64) Artifact
          command: zip -r dist/artifacts/Windows-amd64.zip dist/Windows-amd64
      - store_artifacts:
          path: dist/artifacts/Windows-amd64.zip
          destination: Windows-amd64.zip

      # Produce the macOS Artifact
      - run:
          name: ZIP the macOS (AMD64) Artifact
          command: zip -r dist/artifacts/macOS-amd64.zip dist/macOS-amd64
      - store_artifacts:
          path: dist/artifacts/macOS-amd64.zip
          destination: macOS-amd64.zip

      # Produce the Linux Artifact
      - run:
          name: ZIP the Linux (AMD64) Artifact
          command: zip -r dist/artifacts/Linux-amd64.zip dist/Linux-amd64
      - store_artifacts:
          path: dist/artifacts/Linux-amd64.zip
          destination: Linux-amd64.zip


workflows:
  build:
    jobs:
      - build-caffeinated:
          filters:
              branches:
                only:
                  - production
                  - test
