version: 2.1

jobs:
  build-caffeinated:
    docker:
      - image: cimg/openjdk:11.0-node # We need JDK 11 and NodeJS.
    resource_class: medium # `small` is just *barely* enough, so we spec up a tier.

    steps:
      - checkout

      # Build and produce the artifacts.
      - run:
          name: Build Caffeinated
          command: cd caffeinated && bash build.sh

      # Upload the slim/nojre artifacts to Circle.
      - store_artifacts:
          path: caffeinated/dist/artifacts/Windows-amd64-nojre.zip
          destination: Windows-amd64-nojre.zip
      - store_artifacts:
          path: caffeinated/dist/artifacts/macOS-amd64-nojre.zip
          destination: macOS-amd64-nojre.zip
      - store_artifacts:
          path: caffeinated/dist/artifacts/Linux-amd64-nojre.zip
          destination: Linux-amd64-nojre.zip

      # Upload the regular artifacts to Circle.
      - store_artifacts:
          path: caffeinated/dist/artifacts/Windows-amd64.zip
          destination: Windows-amd64.zip
      - store_artifacts:
          path: caffeinated/dist/artifacts/macOS-amd64.zip
          destination: macOS-amd64.zip
      - store_artifacts:
          path: caffeinated/dist/artifacts/Linux-amd64.zip
          destination: Linux-amd64.zip

  build-caffeinated-updater:
    docker:
      - image: cimg/openjdk:11.0 # We need JDK 11.
    resource_class: small
    steps:
      - checkout

      # Build and produce the artifacts.
      - run:
          name: Build Caffeinated Updater
          command: cd caffeinated/updater && bash build.sh

      # Upload the artifacts to Circle.
      - store_artifacts:
          path: caffeinated/updater/dist/artifacts/Windows.zip
          destination: Casterlabs-Caffeinated-Windows.zip
      - store_artifacts:
          path: caffeinated/updater/dist/artifacts/macOS.tar.gz
          destination: Casterlabs-Caffeinated-macOS.tar.gz
      - store_artifacts:
          path: caffeinated/updater/dist/artifacts/Linux.tar.gz
          destination: Casterlabs-Caffeinated-Linux.tar.gz

workflows:
  build:
    jobs:
      - build-caffeinated:
          filters:
            branches:
              only:
                - alpha
                - beta
                - stable
      - build-caffeinated-updater:
          filters:
            branches:
              only:
                - updater-release
